binop_seperator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
combine_control_expr = false
wrap_comments = true
comment_width = 120
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 80
fn_args_layout = "Vertical"
fn_single_line = false
force_multiline_blocks = true
format_code_in_doc_comment = true
format_strings = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_arm_blocks = true
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "Crate"
merge_inputs = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = true
spaces_around_ranges = true
struct_field_align_threshold = 80
struct_lit_single_line = false
tab_spaces = 2
type_punctuation_density = "Wide"
